version: '3.7'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend